import { type TelemetryState } from "@/services/telemetry-store";

export function buildTelemetryState(
  overrides: Partial<TelemetryState> = {},
): TelemetryState {
  return {
    connectionState: "open",
    lastMessageAt: 2_000,
    health: {
      state: "online",
      capture_available: true,
      message: "Capture stable",
      sweep_path: "hackrf_sweep",
      last_error: null,
    },
    status: {
      started_at_ms: 1_000,
      current_mode: "live",
      last_sweep_sequence: 77,
      last_sweep_at_ms: 1_900,
      metrics: {
        sweep_count: 77,
        peak_count: 12,
        anomaly_count: 4,
        alert_count: 3,
        igor_count: 2,
        reconnect_attempts: 0,
        sweeps_per_second: 1.5,
        peaks_per_second: 0.4,
        anomalies_per_second: 0.1,
        alerts_per_second: 0.08,
        igor_per_second: 0.03,
      },
      config: {
        freq_range_mhz: "2400:2500",
        bin_width_hz: 1_000_000,
        peak_threshold_db: -35,
        occupancy_window_seconds: 300,
        occupancy_recent_window_seconds: 60,
        igor_correlation_window_seconds: 30,
        igor_score_threshold: 60,
      },
      current_recording: {
        active: false,
        session_id: null,
        file_path: null,
        started_at_ms: null,
        event_count: 0,
      },
      current_playback: {
        active: false,
        file_path: null,
        speed: 1,
        started_at_ms: null,
        emitted_events: 0,
      },
    },
    recordingStatus: {
      active: false,
      session_id: null,
      file_path: null,
      started_at_ms: null,
      event_count: 0,
    },
    playbackStatus: {
      active: false,
      file_path: null,
      speed: 1,
      started_at_ms: null,
      emitted_events: 0,
    },
    occupancy: {
      generated_at_ms: 1_950,
      window_seconds: 300,
      bins: [
        {
          frequency_hz: 2_412_000_000,
          activity_percentage: 32.4,
          average_power: -41.2,
          active_duration_seconds: 12,
          window_seconds: 300,
          recent_activity_percentage: 46.1,
          baseline_activity_percentage: 18.6,
        },
      ],
    },
    sweeps: [
      {
        sequence: 77,
        captured_at_ms: 1_900,
        timestamp: "1970-01-01T00:00:01.900Z",
        frequency_start_hz: 2_400_000_000,
        frequency_end_hz: 2_408_000_000,
        bin_width_hz: 1_000_000,
        sample_count: 8,
        power_values: [-44, -40, -31, -18, -26, -34, -42, -46],
      },
    ],
    peaks: [
      {
        timestamp: "1970-01-01T00:00:01.900Z",
        detected_at_ms: 1_900,
        source_sequence: 77,
        start_bin_index: 2,
        end_bin_index: 4,
        frequency: 2_403_000_000,
        frequency_start_hz: 2_402_000_000,
        frequency_end_hz: 2_404_000_000,
        bandwidth_hz: 2_000_000,
        max_power: -18,
        average_power: -25,
      },
    ],
    anomalies: [
      {
        id: "anomaly-1",
        detected_at_ms: 1_850,
        source_sequence: 76,
        anomaly_type: "power_spike",
        severity: "high",
        frequency_start_hz: 2_402_000_000,
        frequency_end_hz: 2_404_000_000,
        max_power: -18,
        message: "Power spike detected near 2.403 GHz.",
      },
    ],
    alerts: [
      {
        id: "alert-1",
        alert_type: "coincident_pulse_spike",
        severity: "critical",
        message: "Pulse spike and burst activity overlapped.",
        detected_at_ms: 1_870,
        source_sequence: 76,
        frequency_start_hz: 2_402_000_000,
        frequency_end_hz: 2_404_000_000,
        power: -17,
      },
      {
        id: "alert-2",
        alert_type: "abnormal_occupancy",
        severity: "medium",
        message: "Occupancy remained elevated.",
        detected_at_ms: 1_840,
        source_sequence: 75,
        frequency_start_hz: 2_412_000_000,
        frequency_end_hz: 2_413_000_000,
        power: -39,
      },
    ],
    igorAssessments: [
      {
        id: "igor-1",
        generated_at_ms: 1_880,
        source_sequence: 76,
        finding_kind: "coordinated_emitter",
        severity: "critical",
        risk_score: 92,
        frequency_start_hz: 2_402_000_000,
        frequency_end_hz: 2_404_000_000,
        evidence_count: 4,
        distinct_anomaly_types: ["power_spike", "repeated_pulses"],
        max_power: -17,
        message: "IGOR correlated repeated pulses with elevated power.",
      },
    ],
    ...overrides,
  };
}
